In [1]:
from traceback import print_tb

import torch
import numpy as np

6.3.1 基本张量创建

（1）按内容创建

In [2]:
# 传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor(10)
torch.Size([])
torch.int64


In [3]:
# 传入一个一维数组
tensor2 = torch.tensor([1.0, 2, 3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([1., 2., 3.])
torch.Size([3])
torch.float32


In [4]:
# 传入一个二维数组
tensor3 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


(2) 创建指定形状的张量

In [5]:
tensor1 = torch.Tensor(3, 2, 4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([3, 2, 4])
torch.float32


In [6]:
tensor2 = torch.Tensor(np.array([[1.10, 2, 3, 4], [4, 5, 6, 7]]))
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([[1.1000, 2.0000, 3.0000, 4.0000],
        [4.0000, 5.0000, 6.0000, 7.0000]])
torch.Size([2, 4])
torch.float32


In [7]:
# 传入一个标量
tensor1 = torch.Tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])
torch.float32


(3)创建指定类型的张量

In [8]:
# int(int32)类型
tensor1 = torch.IntTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int32)
print(tensor1.dtype)
print(tensor2.dtype)


torch.int32
torch.int32


In [9]:
# int(int64)类型
tensor1 = torch.LongTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)


torch.int64
torch.int64


In [10]:
# int(int16)类型
tensor1 = torch.ShortTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.short)
print(tensor1.dtype)
print(tensor2.dtype)


torch.int16
torch.int16


In [11]:
# int(int8)类型
tensor1 = torch.ByteTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.uint8)
print(tensor1.dtype)
print(tensor2.dtype)


torch.uint8
torch.uint8


In [12]:
# float(float32)类型
tensor1 = torch.FloatTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float32)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)


torch.float32
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# double(float32)类型
tensor1 = torch.DoubleTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)


torch.float64
torch.float64
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [14]:
# half类型
tensor1 = torch.HalfTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float16)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)


torch.float16
torch.float16
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [15]:
# boolean类型
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([True, False, True], dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)

torch.bool
torch.bool
tensor([[False, False, False],
        [False, False, False]])


6.3.2 指定区间的张量创建

In [17]:
tensor1 = torch.arange(10, 30, 2)
print(tensor1)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])


In [18]:
tensor2 = torch.arange(6)
print(tensor2)

tensor([0, 1, 2, 3, 4, 5])


In [20]:
# 指明在某一个闭区间内生成x个元素
tensor1 = torch.linspace(10, 30, 6)
print(tensor1)

tensor([10., 14., 18., 22., 26., 30.])


In [22]:
tensor1 = torch.logspace(1, 3, 3, base=2)
print(tensor1)

tensor([2., 4., 8.])


6.3.3 按数值填充创建张量

In [25]:
tensor1 = torch.zeros(2, 3, 4)
print(tensor1)
print(tensor1.dtype)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.float32


In [26]:
tensor2 = torch.ones_like(tensor1)
print(tensor2)
print(tensor2.dtype)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.float32


In [30]:
tensor1 = torch.full((3, 2), 6.4)
print(tensor1)
print(tensor1.dtype)

tensor([[6.4000, 6.4000],
        [6.4000, 6.4000],
        [6.4000, 6.4000]])
torch.float32


In [33]:
tensor2 = torch.empty_like(tensor1)
print(tensor2)
print(tensor2.dtype)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
torch.float32


In [38]:
tensor1 = torch.eye(3, 5)
print(tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


6.3.4 随机张量创建

In [40]:
tensor1 = torch.rand(2, 3)
print(tensor1)

tensor([[0.8643, 0.1713, 0.0278],
        [0.5501, 0.4335, 0.5293]])


In [41]:
tensor2 = torch.rand_like(tensor1)
print(tensor2)

tensor([[0.3352, 0.5267, 0.9263],
        [0.3962, 0.1864, 0.0166]])


In [43]:
tensor1 = torch.randint(low=0, high=100, size=(2, 3))
print(tensor1)

tensor([[ 1, 58, 52],
        [95, 60,  1]])


In [45]:
tensor2 = torch.randint_like(tensor1, low=10, high=100)
print(tensor2)

tensor([[68, 55, 57],
        [24, 19, 65]])


In [46]:
tensor1 = torch.randn(4, 2)
print(tensor1)

tensor([[-1.1367, -0.3819],
        [ 0.1900,  0.0196],
        [-1.9739,  0.5213],
        [-1.3433,  0.2848]])


In [47]:
tensor2 = torch.randn_like(tensor1)
print(tensor2)

tensor([[ 0.2032,  0.9513],
        [-2.4083, -0.1081],
        [ 1.7902,  0.3066],
        [-1.1626, -0.9248]])


In [48]:
tensor1 = torch.normal(5, 2, tensor2.shape)
print(tensor1)

tensor([[4.7442, 5.4327],
        [3.6609, 1.3191],
        [2.3601, 2.5709],
        [6.9523, 5.8763]])


In [49]:
tensor1 = torch.randperm(10)
print(tensor1)

tensor([5, 7, 1, 2, 3, 8, 4, 6, 0, 9])


In [50]:
torch.random.initial_seed()

17084933069060924769