In [1]:
import numpy as np
import torch

6.4.1 张量元素类型转换

In [2]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1)
print(tensor1.dtype)

tensor([1, 2, 3])
torch.int64


In [4]:
tensor1 = tensor1.type(torch.float32)
print(tensor1)
print(tensor1.dtype)

tensor([1., 2., 3.])
torch.float32


In [6]:
tensor1 = tensor1.double()
print(tensor1)
print(tensor1.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


In [8]:
tensor1 = tensor1.to(dtype=torch.complex64)
print(tensor1)
print(tensor1.dtype)

tensor([1.+0.j, 2.+0.j, 3.+0.j])
torch.complex64


6.4.2 tensor和ndarray转换

In [9]:
# tensor -> ndarray
tensor1 = torch.rand(3, 2)
print(tensor1)

tensor([[0.3678, 0.8062],
        [0.6670, 0.2633],
        [0.7403, 0.4878]])


In [10]:
ndarray1 = tensor1.numpy()
print(ndarray1)

[[0.36775595 0.80622935]
 [0.6669579  0.26331633]
 [0.7402904  0.4877721 ]]


In [12]:
tensor1[:, 0] = 10
print(tensor1)

tensor([[10.0000,  0.8062],
        [10.0000,  0.2633],
        [10.0000,  0.4878]])


In [13]:
print(ndarray1)

[[10.          0.80622935]
 [10.          0.26331633]
 [10.          0.4877721 ]]


In [14]:
# 使用copy方法避免共享内存
ndarray2 = tensor1.numpy().copy()
print(ndarray2)

[[10.          0.80622935]
 [10.          0.26331633]
 [10.          0.4877721 ]]


In [17]:
tensor1[:, 0] = 5
print(tensor1)
print(ndarray1)
print(ndarray2)

tensor([[5.0000, 0.8062],
        [5.0000, 0.2633],
        [5.0000, 0.4878]])
[[5.         0.80622935]
 [5.         0.26331633]
 [5.         0.4877721 ]]
[[10.          0.80622935]
 [10.          0.26331633]
 [10.          0.4877721 ]]


In [18]:
# 从ndarray转换为tensor
ndarray1 = np.random.randn(3, 2)
tensor1 = torch.from_numpy(ndarray1)
print(ndarray1)
print(tensor1)

[[-0.87671127  1.61325752]
 [-0.7167246  -0.78163323]
 [ 0.91819334 -2.01431757]]
tensor([[-0.8767,  1.6133],
        [-0.7167, -0.7816],
        [ 0.9182, -2.0143]], dtype=torch.float64)


In [19]:
ndarray1[:, 0] = 5
print(ndarray1)
print(tensor1)

[[ 5.          1.61325752]
 [ 5.         -0.78163323]
 [ 5.         -2.01431757]]
tensor([[ 5.0000,  1.6133],
        [ 5.0000, -0.7816],
        [ 5.0000, -2.0143]], dtype=torch.float64)


In [20]:
tensor2 = torch.from_numpy(ndarray1.copy())
ndarray1[:, 0] = 7
print(tensor2)
print(tensor1)

tensor([[ 5.0000,  1.6133],
        [ 5.0000, -0.7816],
        [ 5.0000, -2.0143]], dtype=torch.float64)
tensor([[ 7.0000,  1.6133],
        [ 7.0000, -0.7816],
        [ 7.0000, -2.0143]], dtype=torch.float64)


In [21]:
# 使用tengsor方法直接转换成张量tensor
ndarray1 = np.random.randn(3, 2)
tensor1 = torch.tensor(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[-0.2093,  0.3974],
        [-1.2951, -1.2644],
        [ 0.0901, -0.9878]], dtype=torch.float64)
[[-0.20929621  0.39740301]
 [-1.29508074 -1.26436377]
 [ 0.09014036 -0.98784163]]


In [23]:
ndarray1[:, 0] = 9
print(tensor1)
print(ndarray1)

tensor([[-0.2093,  0.3974],
        [-1.2951, -1.2644],
        [ 0.0901, -0.9878]], dtype=torch.float64)
[[ 9.          0.39740301]
 [ 9.         -1.26436377]
 [ 9.         -0.98784163]]


In [24]:
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.item())

tensor(10)
10


In [25]:
tensor1 = torch.tensor([10])
print(tensor1)
print(tensor1.item())

tensor([10])
10


In [26]:
tensor1 = torch.tensor([[10]])
print(tensor1)
print(tensor1.item())

tensor([[10]])
10


In [27]:
tensor1 = torch.tensor([10, 2])
print(tensor1)
print(tensor1.item())

tensor([10,  2])


RuntimeError: a Tensor with 2 elements cannot be converted to Scalar