In [1]:
from sndhdr import test_sndr

import torch

In [2]:
# 1. 四则运算
tensor1 = torch.randint(low=0, high=10, size=(2, 3))
print(tensor1)

tensor([[5, 3, 7],
        [1, 5, 7]])


In [3]:
tensor1 + 10

tensor([[15, 13, 17],
        [11, 15, 17]])

In [4]:
tensor1

tensor([[5, 3, 7],
        [1, 5, 7]])

In [5]:
tensor1.add(10)

tensor([[15, 13, 17],
        [11, 15, 17]])

In [6]:
tensor1

tensor([[5, 3, 7],
        [1, 5, 7]])

In [7]:
tensor1.add_(10)

tensor([[15, 13, 17],
        [11, 15, 17]])

In [8]:
tensor1

tensor([[15, 13, 17],
        [11, 15, 17]])

In [9]:
# 幂函数
tensor1 ** 2

tensor([[225, 169, 289],
        [121, 225, 289]])

In [10]:
tensor1

tensor([[15, 13, 17],
        [11, 15, 17]])

In [11]:
tensor1.pow(2)

tensor([[225, 169, 289],
        [121, 225, 289]])

In [12]:
tensor1

tensor([[15, 13, 17],
        [11, 15, 17]])

In [13]:
tensor1.pow_(2)

tensor([[225, 169, 289],
        [121, 225, 289]])

In [14]:
tensor1

tensor([[225, 169, 289],
        [121, 225, 289]])

In [15]:
tensor1.pow(0.5)

tensor([[15., 13., 17.],
        [11., 15., 17.]])

In [16]:
tensor1.sqrt()

tensor([[15., 13., 17.],
        [11., 15., 17.]])

In [17]:
tensor1

tensor([[225, 169, 289],
        [121, 225, 289]])

In [18]:
tensor1.sqrt()

tensor([[15., 13., 17.],
        [11., 15., 17.]])

In [19]:
tensor1.sqrt_()

RuntimeError: result type Float can't be cast to the desired output type Long

In [20]:
tensor1.float()

tensor([[225., 169., 289.],
        [121., 225., 289.]])

In [21]:
tensor1

tensor([[225, 169, 289],
        [121, 225, 289]])

In [23]:
tensor1.dtype = torch.float

AttributeError: attribute 'dtype' of 'torch._C.TensorBase' objects is not writable

In [24]:
tensor1 = tensor1.float()

In [25]:
tensor1

tensor([[225., 169., 289.],
        [121., 225., 289.]])

In [26]:
tensor1.sqrt_()

tensor([[15., 13., 17.],
        [11., 15., 17.]])

In [27]:
tensor1 = torch.tensor([1.0, 2, 3])

In [28]:
tensor1

tensor([1., 2., 3.])

In [29]:
tensor1.dtype

torch.float32

In [30]:
tensor1.exp()

tensor([ 2.7183,  7.3891, 20.0855])

In [31]:
tensor1

tensor([1., 2., 3.])

In [32]:
# 计算张量的哈达玛积
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])

In [33]:
tensor1 + tensor2

tensor([[2, 4],
        [6, 8]])

In [34]:
tensor1 * tensor2

tensor([[ 1,  4],
        [ 9, 16]])

In [35]:
tensor1.mul(tensor2)

tensor([[ 1,  4],
        [ 9, 16]])

In [36]:
tensor1.mul_(tensor2)

tensor([[ 1,  4],
        [ 9, 16]])

In [37]:
tensor1

tensor([[ 1,  4],
        [ 9, 16]])

In [38]:
# 张量乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [39]:
tensor1 @ tensor2

tensor([[22, 28],
        [49, 64]])

In [40]:
tensor1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
tensor2

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [42]:
tensor1.mm(tensor2)

tensor([[22, 28],
        [49, 64]])

In [43]:
tensor1.matmul(tensor2)

tensor([[22, 28],
        [49, 64]])

In [44]:
tensor1 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[6, 5, 4], [3, 2, 1]]])
tensor2 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[6, 5], [4, 3], [2, 1]]])

In [45]:
tensor1.size()

torch.Size([2, 2, 3])

In [46]:
tensor2.size()

torch.Size([2, 3, 2])

In [48]:
tensor3 = tensor1.matmul(tensor2)

In [49]:
tensor3

tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])

In [50]:
tensor3.size()

torch.Size([2, 2, 2])

In [56]:
# 验证内存的共享和节省内存
X = torch.randint(1, 10, (3, 2, 4))
X
print(id(X))

4488704896


In [57]:
# X = X + 10
X += 10
print("after plus: ", id(X))

after plus:  4488704896


In [53]:
X

tensor([[[15, 19, 19, 11],
         [13, 15, 12, 13]],

        [[14, 11, 18, 13],
         [11, 16, 13, 17]],

        [[13, 14, 13, 12],
         [16, 18, 13, 12]]])

In [60]:
X = torch.randint(1, 10, (3, 2, 4))
Y = torch.randint(1, 10, (3, 4, 1))
print(X.size())
print(id(X))
print(X)
print(Y)
print(X @ Y)
# X = X @ Y
X[:] = (X @ Y)
print(X)
print(X.size())
print(id(X))

torch.Size([3, 2, 4])
4488824608
tensor([[[8, 2, 3, 9],
         [6, 8, 6, 8]],

        [[2, 8, 6, 2],
         [4, 7, 2, 5]],

        [[3, 6, 2, 8],
         [6, 8, 3, 3]]])
tensor([[[2],
         [8],
         [2],
         [3]],

        [[1],
         [4],
         [6],
         [4]],

        [[4],
         [5],
         [8],
         [6]]])
tensor([[[ 65],
         [112]],

        [[ 78],
         [ 64]],

        [[106],
         [106]]])
tensor([[[ 65,  65,  65,  65],
         [112, 112, 112, 112]],

        [[ 78,  78,  78,  78],
         [ 64,  64,  64,  64]],

        [[106, 106, 106, 106],
         [106, 106, 106, 106]]])
torch.Size([3, 2, 4])
4488824608
