In [1]:
import torch

In [2]:
tensor1 = torch.randint(1, 10, (3, 2, 4))

In [3]:
tensor1

tensor([[[3, 8, 6, 7],
         [8, 3, 8, 3]],

        [[4, 2, 1, 1],
         [8, 3, 4, 1]],

        [[5, 4, 5, 7],
         [6, 3, 2, 1]]])

In [4]:
# sum求和
print(tensor1.sum())

tensor(103)


In [8]:
tensor1.sum(dim=2)

tensor([[24, 22],
        [ 8, 16],
        [21, 12]])

In [11]:
# mean求均值
tensor1 = torch.randint(1, 10, (3, 2, 4)).float()
tensor1.mean(dim=2)

tensor([[5.0000, 7.2500],
        [5.5000, 6.5000],
        [7.0000, 7.7500]])

In [12]:
# std求标准房差
tensor1.std()

tensor(2.1468)

In [18]:
# max, min 求最大最小值
tensor1.max()

tensor(9.)

In [19]:
tensor1

tensor([[[7., 8., 2., 3.],
         [9., 5., 6., 9.]],

        [[3., 6., 5., 8.],
         [9., 7., 3., 7.]],

        [[8., 6., 9., 5.],
         [7., 7., 9., 8.]]])

In [17]:
tensor1.min(dim=2)

torch.return_types.min(
values=tensor([[2., 5.],
        [3., 3.],
        [5., 7.]]),
indices=tensor([[2, 1],
        [0, 2],
        [3, 0]]))

In [15]:
tensor1.argmin(dim=2)

tensor([[2, 1],
        [0, 2],
        [3, 0]])

In [20]:
# 去重
tensor1.unique()

tensor([2., 3., 5., 6., 7., 8., 9.])

In [21]:
# 排序
tensor1.sort()

torch.return_types.sort(
values=tensor([[[2., 3., 7., 8.],
         [5., 6., 9., 9.]],

        [[3., 5., 6., 8.],
         [3., 7., 7., 9.]],

        [[5., 6., 8., 9.],
         [7., 7., 8., 9.]]]),
indices=tensor([[[2, 3, 0, 1],
         [1, 2, 0, 3]],

        [[0, 2, 1, 3],
         [2, 1, 3, 0]],

        [[3, 1, 0, 2],
         [0, 1, 3, 2]]]))