In [1]:
import torch

In [2]:
tensor1 = torch.randint(1, 10, (3, 5, 4))

In [3]:
tensor1

tensor([[[3, 9, 9, 9],
         [6, 6, 7, 7],
         [1, 7, 7, 8],
         [3, 5, 4, 7],
         [2, 3, 5, 3]],

        [[9, 5, 3, 9],
         [7, 1, 6, 7],
         [3, 2, 3, 4],
         [7, 9, 4, 8],
         [6, 9, 7, 5]],

        [[8, 4, 3, 3],
         [6, 5, 3, 8],
         [5, 6, 2, 6],
         [8, 7, 7, 9],
         [1, 7, 3, 9]]])

In [4]:
# 简单索引操作
tensor1[2, 1, 3]

tensor(8)

In [5]:
tensor1[2, 3]

tensor([8, 7, 7, 9])

In [6]:
print(tensor1[1])

tensor([[9, 5, 3, 9],
        [7, 1, 6, 7],
        [3, 2, 3, 4],
        [7, 9, 4, 8],
        [6, 9, 7, 5]])


In [8]:
tensor1[:, 3]

tensor([[3, 5, 4, 7],
        [7, 9, 4, 8],
        [8, 7, 7, 9]])

In [9]:
# 范围索引
tensor1[1:]

tensor([[[9, 5, 3, 9],
         [7, 1, 6, 7],
         [3, 2, 3, 4],
         [7, 9, 4, 8],
         [6, 9, 7, 5]],

        [[8, 4, 3, 3],
         [6, 5, 3, 8],
         [5, 6, 2, 6],
         [8, 7, 7, 9],
         [1, 7, 3, 9]]])

In [11]:
tensor1[-1:, 1:4, 0:3]

tensor([[[6, 5, 3],
         [5, 6, 2],
         [8, 7, 7]]])

In [14]:
# 列表索引
print(tensor1)

tensor([[[3, 9, 9, 9],
         [6, 6, 7, 7],
         [1, 7, 7, 8],
         [3, 5, 4, 7],
         [2, 3, 5, 3]],

        [[9, 5, 3, 9],
         [7, 1, 6, 7],
         [3, 2, 3, 4],
         [7, 9, 4, 8],
         [6, 9, 7, 5]],

        [[8, 4, 3, 3],
         [6, 5, 3, 8],
         [5, 6, 2, 6],
         [8, 7, 7, 9],
         [1, 7, 3, 9]]])


In [16]:
tensor1[[0, 1], [1, 2]]

tensor([[6, 6, 7, 7],
        [3, 2, 3, 4]])

In [17]:
tensor1[[0, 1], [3, 2]]

tensor([[3, 5, 4, 7],
        [3, 2, 3, 4]])

In [18]:
tensor1[[0, 1], [3, 2], [0]]

tensor([3, 3])

In [19]:
tensor1[[0, 1], [3, 2], [2, 3]]

tensor([4, 4])

In [20]:
tensor1[[[0], [1]], [1, 2]]

tensor([[[6, 6, 7, 7],
         [1, 7, 7, 8]],

        [[7, 1, 6, 7],
         [3, 2, 3, 4]]])

In [27]:
# 布尔索引
# 1. 选取符合条件的行：首行元素大于5
mask = tensor1[:,:, 0] > 5

In [28]:
mask

tensor([[False,  True, False, False, False],
        [ True,  True, False,  True,  True],
        [ True,  True, False,  True, False]])

In [31]:
print(tensor1[mask])
print(tensor1[mask].size())

tensor([[6, 6, 7, 7],
        [9, 5, 3, 9],
        [7, 1, 6, 7],
        [7, 9, 4, 8],
        [6, 9, 7, 5],
        [8, 4, 3, 3],
        [6, 5, 3, 8],
        [8, 7, 7, 9]])
torch.Size([8, 4])


In [32]:
# 选取符合条件的列：第二列元素大于5
mask = tensor1[:, 1, :] > 5

In [33]:
mask

tensor([[ True,  True,  True,  True],
        [ True, False,  True,  True],
        [ True, False, False,  True]])

In [36]:
tensor2 = tensor1.mT

In [37]:
tensor2

tensor([[[3, 6, 1, 3, 2],
         [9, 6, 7, 5, 3],
         [9, 7, 7, 4, 5],
         [9, 7, 8, 7, 3]],

        [[9, 7, 3, 7, 6],
         [5, 1, 2, 9, 9],
         [3, 6, 3, 4, 7],
         [9, 7, 4, 8, 5]],

        [[8, 6, 5, 8, 1],
         [4, 5, 6, 7, 7],
         [3, 3, 2, 7, 3],
         [3, 8, 6, 9, 9]]])

In [38]:
tensor2[mask]

tensor([[3, 6, 1, 3, 2],
        [9, 6, 7, 5, 3],
        [9, 7, 7, 4, 5],
        [9, 7, 8, 7, 3],
        [9, 7, 3, 7, 6],
        [3, 6, 3, 4, 7],
        [9, 7, 4, 8, 5],
        [8, 6, 5, 8, 1],
        [3, 8, 6, 9, 9]])

In [39]:
tensor2[mask].T

tensor([[3, 9, 9, 9, 9, 3, 9, 8, 3],
        [6, 6, 7, 7, 7, 6, 7, 6, 8],
        [1, 7, 7, 8, 3, 3, 4, 5, 6],
        [3, 5, 4, 7, 7, 4, 8, 8, 9],
        [2, 3, 5, 3, 6, 7, 5, 1, 9]])

In [40]:
# 选取符合条件的矩阵：<1, 2> > 5
mask = tensor1[:, 1, 2] > 5

In [41]:
mask

tensor([ True,  True, False])

In [42]:
tensor1[mask]

tensor([[[3, 9, 9, 9],
         [6, 6, 7, 7],
         [1, 7, 7, 8],
         [3, 5, 4, 7],
         [2, 3, 5, 3]],

        [[9, 5, 3, 9],
         [7, 1, 6, 7],
         [3, 2, 3, 4],
         [7, 9, 4, 8],
         [6, 9, 7, 5]]])

In [43]:
tensor1[tensor1 > 5]

tensor([9, 9, 9, 6, 6, 7, 7, 7, 7, 8, 7, 9, 9, 7, 6, 7, 7, 9, 8, 6, 9, 7, 8, 6,
        8, 6, 6, 8, 7, 7, 9, 7, 9])