In [1]:
from pickletools import read_decimalnl_short

import torch

In [2]:
tensor1 = torch.randint(1, 10, (2, 3, 6))

In [3]:
tensor1

tensor([[[3, 9, 3, 2, 9, 1],
         [8, 8, 2, 9, 5, 6],
         [4, 6, 8, 6, 8, 5]],

        [[7, 1, 4, 9, 9, 3],
         [7, 6, 7, 1, 1, 5],
         [7, 5, 8, 9, 5, 4]]])

In [5]:
# 交换维度
tensor1.transpose(0, 2)

tensor([[[3, 7],
         [8, 7],
         [4, 7]],

        [[9, 1],
         [8, 6],
         [6, 5]],

        [[3, 4],
         [2, 7],
         [8, 8]],

        [[2, 9],
         [9, 1],
         [6, 9]],

        [[9, 9],
         [5, 1],
         [8, 5]],

        [[1, 3],
         [6, 5],
         [5, 4]]])

In [6]:
# 重新排列多个维度
tensor1.permute(0, 2, 1)

tensor([[[3, 8, 4],
         [9, 8, 6],
         [3, 2, 8],
         [2, 9, 6],
         [9, 5, 8],
         [1, 6, 5]],

        [[7, 7, 7],
         [1, 6, 5],
         [4, 7, 8],
         [9, 1, 9],
         [9, 1, 5],
         [3, 5, 4]]])

In [7]:
# 调整形状
tensor1 = torch.randint(1, 10, (3, 5, 4))

In [8]:
tensor1

tensor([[[5, 8, 9, 5],
         [3, 6, 6, 7],
         [2, 2, 3, 9],
         [2, 6, 8, 8],
         [7, 1, 4, 2]],

        [[4, 7, 6, 3],
         [2, 2, 5, 3],
         [9, 9, 2, 5],
         [5, 7, 6, 5],
         [9, 3, 6, 8]],

        [[9, 6, 1, 2],
         [7, 6, 4, 5],
         [4, 6, 6, 1],
         [3, 1, 6, 1],
         [5, 6, 6, 8]]])

In [9]:
tensor1.shape

torch.Size([3, 5, 4])

In [10]:
tensor1.reshape(6, 10)

tensor([[5, 8, 9, 5, 3, 6, 6, 7, 2, 2],
        [3, 9, 2, 6, 8, 8, 7, 1, 4, 2],
        [4, 7, 6, 3, 2, 2, 5, 3, 9, 9],
        [2, 5, 5, 7, 6, 5, 9, 3, 6, 8],
        [9, 6, 1, 2, 7, 6, 4, 5, 4, 6],
        [6, 1, 3, 1, 6, 1, 5, 6, 6, 8]])

In [11]:
tensor1.reshape(-1)

tensor([5, 8, 9, 5, 3, 6, 6, 7, 2, 2, 3, 9, 2, 6, 8, 8, 7, 1, 4, 2, 4, 7, 6, 3,
        2, 2, 5, 3, 9, 9, 2, 5, 5, 7, 6, 5, 9, 3, 6, 8, 9, 6, 1, 2, 7, 6, 4, 5,
        4, 6, 6, 1, 3, 1, 6, 1, 5, 6, 6, 8])

In [12]:
tensor1.reshape(3, -1)

tensor([[5, 8, 9, 5, 3, 6, 6, 7, 2, 2, 3, 9, 2, 6, 8, 8, 7, 1, 4, 2],
        [4, 7, 6, 3, 2, 2, 5, 3, 9, 9, 2, 5, 5, 7, 6, 5, 9, 3, 6, 8],
        [9, 6, 1, 2, 7, 6, 4, 5, 4, 6, 6, 1, 3, 1, 6, 1, 5, 6, 6, 8]])

In [13]:
tensor1.is_contiguous()

True

In [14]:
tensor1.view(-1, 10)

tensor([[5, 8, 9, 5, 3, 6, 6, 7, 2, 2],
        [3, 9, 2, 6, 8, 8, 7, 1, 4, 2],
        [4, 7, 6, 3, 2, 2, 5, 3, 9, 9],
        [2, 5, 5, 7, 6, 5, 9, 3, 6, 8],
        [9, 6, 1, 2, 7, 6, 4, 5, 4, 6],
        [6, 1, 3, 1, 6, 1, 5, 6, 6, 8]])

In [16]:
tensor1.shape

torch.Size([3, 5, 4])

In [20]:
 # 对张量进行转置
 t1 = tensor1.permute(2, 1, 0)

In [21]:
t1.is_contiguous()

False

In [22]:
t1.view(-1, 10)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [24]:
t1.contiguous().view(-1, 10)

tensor([[5, 4, 9, 3, 2, 7, 2, 9, 4, 2],
        [5, 3, 7, 9, 5, 8, 7, 6, 6, 2],
        [6, 2, 9, 6, 6, 7, 1, 1, 3, 6],
        [9, 6, 1, 6, 5, 4, 3, 2, 6, 8],
        [6, 6, 4, 6, 6, 5, 3, 2, 7, 3],
        [5, 9, 5, 1, 8, 5, 1, 2, 8, 8]])

In [25]:
# 增加或删除维度

In [26]:
tensor1 = torch.tensor([1, 2, 3])

In [27]:
tensor1

tensor([1, 2, 3])

In [29]:
# 在0维上增加一个维度
tensor1.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3]])

In [30]:
tensor1.unsqueeze_(dim=0)

tensor([[1, 2, 3]])

In [31]:
# 减少维度：降维
tensor1

tensor([[1, 2, 3]])

In [33]:
tensor1.squeeze(dim=0)

tensor([1, 2, 3])

In [34]:
## 张量拼接

In [35]:
tensor1 = torch.randint(1, 10, (2, 2, 5))

In [36]:
tensor2 = torch.randint(1, 10, (2, 3, 5))

In [37]:
tensor1

tensor([[[8, 9, 5, 5, 9],
         [7, 4, 1, 6, 2]],

        [[9, 8, 6, 9, 1],
         [5, 4, 3, 4, 3]]])

In [38]:
tensor2

tensor([[[2, 5, 2, 1, 1],
         [5, 4, 9, 4, 5],
         [6, 3, 9, 1, 6]],

        [[5, 9, 6, 4, 2],
         [4, 3, 1, 5, 2],
         [8, 6, 5, 3, 6]]])

In [40]:
torch.cat((tensor1, tensor2), dim=1)

tensor([[[8, 9, 5, 5, 9],
         [7, 4, 1, 6, 2],
         [2, 5, 2, 1, 1],
         [5, 4, 9, 4, 5],
         [6, 3, 9, 1, 6]],

        [[9, 8, 6, 9, 1],
         [5, 4, 3, 4, 3],
         [5, 9, 6, 4, 2],
         [4, 3, 1, 5, 2],
         [8, 6, 5, 3, 6]]])

In [41]:
# 堆叠
tensor1 = torch.randint(1, 10, (4, 3, 5))
tensor2 = torch.randint(1, 10, (4, 3, 5))

In [42]:
tensor1

tensor([[[9, 2, 8, 4, 4],
         [3, 7, 3, 2, 3],
         [7, 6, 9, 8, 1]],

        [[5, 9, 6, 8, 4],
         [7, 9, 1, 4, 8],
         [5, 4, 6, 1, 6]],

        [[5, 5, 3, 8, 6],
         [3, 2, 4, 1, 5],
         [9, 6, 5, 9, 3]],

        [[4, 8, 6, 7, 8],
         [7, 9, 1, 9, 8],
         [4, 4, 9, 8, 7]]])

In [43]:
tensor2

tensor([[[1, 9, 3, 6, 5],
         [8, 2, 9, 3, 6],
         [9, 2, 2, 2, 2]],

        [[6, 9, 6, 5, 7],
         [4, 6, 3, 3, 7],
         [7, 1, 5, 9, 4]],

        [[5, 6, 2, 7, 4],
         [4, 1, 8, 7, 4],
         [8, 7, 7, 5, 5]],

        [[2, 9, 8, 9, 7],
         [8, 1, 2, 8, 9],
         [7, 5, 9, 6, 5]]])

In [53]:
tensor3 = torch.stack((tensor1, tensor2), dim=3)

In [54]:
tensor3.shape

torch.Size([4, 3, 5, 2])